//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExternalServiceCalls.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubrogationInfo", Namespace="http://schemas.datacontract.org/2004/07/AZT.NET.Insurance.Entities.Subrogation")]
    [System.SerializableAttribute()]
    public partial class SubrogationInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmiableAssessmentNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AssessmentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaimFileNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClaimIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaimReserveCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClaimReserveCurrencyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ClaimReserveValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ClaimReserveValueRonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EventBaseTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InsuredCarBrandIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InsuredCarBrandNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InsuredCarChassisNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InsuredCarModelNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InsuredCarPlateNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InsuredFullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InsuredIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InsuredPolicyNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LossCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LossCityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LossCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LossCountryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LossCountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LossCountyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LossDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LossDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LossDistrictNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LossIntersectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LossStreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LossStreetNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReadStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReportingDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubrogationCarChassisNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubrogationCarPlateNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubrogationGuiltyPartnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubrogationInsurerCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubrogationInsurerCountryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubrogationInsurerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubrogationInsurerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubrogationRcoPolicyNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubrogationTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AmiableAssessmentNo {
            get {
                return this.AmiableAssessmentNoField;
            }
            set {
                if ((object.ReferenceEquals(this.AmiableAssessmentNoField, value) != true)) {
                    this.AmiableAssessmentNoField = value;
                    this.RaisePropertyChanged("AmiableAssessmentNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AssessmentDate {
            get {
                return this.AssessmentDateField;
            }
            set {
                if ((this.AssessmentDateField.Equals(value) != true)) {
                    this.AssessmentDateField = value;
                    this.RaisePropertyChanged("AssessmentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaimFileNo {
            get {
                return this.ClaimFileNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaimFileNoField, value) != true)) {
                    this.ClaimFileNoField = value;
                    this.RaisePropertyChanged("ClaimFileNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClaimId {
            get {
                return this.ClaimIdField;
            }
            set {
                if ((this.ClaimIdField.Equals(value) != true)) {
                    this.ClaimIdField = value;
                    this.RaisePropertyChanged("ClaimId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaimReserveCurrency {
            get {
                return this.ClaimReserveCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaimReserveCurrencyField, value) != true)) {
                    this.ClaimReserveCurrencyField = value;
                    this.RaisePropertyChanged("ClaimReserveCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClaimReserveCurrencyId {
            get {
                return this.ClaimReserveCurrencyIdField;
            }
            set {
                if ((this.ClaimReserveCurrencyIdField.Equals(value) != true)) {
                    this.ClaimReserveCurrencyIdField = value;
                    this.RaisePropertyChanged("ClaimReserveCurrencyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ClaimReserveValue {
            get {
                return this.ClaimReserveValueField;
            }
            set {
                if ((this.ClaimReserveValueField.Equals(value) != true)) {
                    this.ClaimReserveValueField = value;
                    this.RaisePropertyChanged("ClaimReserveValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ClaimReserveValueRon {
            get {
                return this.ClaimReserveValueRonField;
            }
            set {
                if ((this.ClaimReserveValueRonField.Equals(value) != true)) {
                    this.ClaimReserveValueRonField = value;
                    this.RaisePropertyChanged("ClaimReserveValueRon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EventBaseType {
            get {
                return this.EventBaseTypeField;
            }
            set {
                if ((this.EventBaseTypeField.Equals(value) != true)) {
                    this.EventBaseTypeField = value;
                    this.RaisePropertyChanged("EventBaseType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InsuredCarBrandId {
            get {
                return this.InsuredCarBrandIdField;
            }
            set {
                if ((this.InsuredCarBrandIdField.Equals(value) != true)) {
                    this.InsuredCarBrandIdField = value;
                    this.RaisePropertyChanged("InsuredCarBrandId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InsuredCarBrandName {
            get {
                return this.InsuredCarBrandNameField;
            }
            set {
                if ((object.ReferenceEquals(this.InsuredCarBrandNameField, value) != true)) {
                    this.InsuredCarBrandNameField = value;
                    this.RaisePropertyChanged("InsuredCarBrandName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InsuredCarChassisNo {
            get {
                return this.InsuredCarChassisNoField;
            }
            set {
                if ((object.ReferenceEquals(this.InsuredCarChassisNoField, value) != true)) {
                    this.InsuredCarChassisNoField = value;
                    this.RaisePropertyChanged("InsuredCarChassisNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InsuredCarModelName {
            get {
                return this.InsuredCarModelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.InsuredCarModelNameField, value) != true)) {
                    this.InsuredCarModelNameField = value;
                    this.RaisePropertyChanged("InsuredCarModelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InsuredCarPlateNo {
            get {
                return this.InsuredCarPlateNoField;
            }
            set {
                if ((object.ReferenceEquals(this.InsuredCarPlateNoField, value) != true)) {
                    this.InsuredCarPlateNoField = value;
                    this.RaisePropertyChanged("InsuredCarPlateNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InsuredFullName {
            get {
                return this.InsuredFullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.InsuredFullNameField, value) != true)) {
                    this.InsuredFullNameField = value;
                    this.RaisePropertyChanged("InsuredFullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InsuredId {
            get {
                return this.InsuredIdField;
            }
            set {
                if ((this.InsuredIdField.Equals(value) != true)) {
                    this.InsuredIdField = value;
                    this.RaisePropertyChanged("InsuredId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InsuredPolicyNo {
            get {
                return this.InsuredPolicyNoField;
            }
            set {
                if ((object.ReferenceEquals(this.InsuredPolicyNoField, value) != true)) {
                    this.InsuredPolicyNoField = value;
                    this.RaisePropertyChanged("InsuredPolicyNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LossCity {
            get {
                return this.LossCityField;
            }
            set {
                if ((object.ReferenceEquals(this.LossCityField, value) != true)) {
                    this.LossCityField = value;
                    this.RaisePropertyChanged("LossCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LossCityId {
            get {
                return this.LossCityIdField;
            }
            set {
                if ((this.LossCityIdField.Equals(value) != true)) {
                    this.LossCityIdField = value;
                    this.RaisePropertyChanged("LossCityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LossCountry {
            get {
                return this.LossCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.LossCountryField, value) != true)) {
                    this.LossCountryField = value;
                    this.RaisePropertyChanged("LossCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LossCountryId {
            get {
                return this.LossCountryIdField;
            }
            set {
                if ((this.LossCountryIdField.Equals(value) != true)) {
                    this.LossCountryIdField = value;
                    this.RaisePropertyChanged("LossCountryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LossCounty {
            get {
                return this.LossCountyField;
            }
            set {
                if ((object.ReferenceEquals(this.LossCountyField, value) != true)) {
                    this.LossCountyField = value;
                    this.RaisePropertyChanged("LossCounty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LossCountyId {
            get {
                return this.LossCountyIdField;
            }
            set {
                if ((this.LossCountyIdField.Equals(value) != true)) {
                    this.LossCountyIdField = value;
                    this.RaisePropertyChanged("LossCountyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LossDate {
            get {
                return this.LossDateField;
            }
            set {
                if ((this.LossDateField.Equals(value) != true)) {
                    this.LossDateField = value;
                    this.RaisePropertyChanged("LossDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LossDescription {
            get {
                return this.LossDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.LossDescriptionField, value) != true)) {
                    this.LossDescriptionField = value;
                    this.RaisePropertyChanged("LossDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LossDistrictNo {
            get {
                return this.LossDistrictNoField;
            }
            set {
                if ((this.LossDistrictNoField.Equals(value) != true)) {
                    this.LossDistrictNoField = value;
                    this.RaisePropertyChanged("LossDistrictNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LossIntersection {
            get {
                return this.LossIntersectionField;
            }
            set {
                if ((object.ReferenceEquals(this.LossIntersectionField, value) != true)) {
                    this.LossIntersectionField = value;
                    this.RaisePropertyChanged("LossIntersection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LossStreet {
            get {
                return this.LossStreetField;
            }
            set {
                if ((object.ReferenceEquals(this.LossStreetField, value) != true)) {
                    this.LossStreetField = value;
                    this.RaisePropertyChanged("LossStreet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LossStreetNo {
            get {
                return this.LossStreetNoField;
            }
            set {
                if ((object.ReferenceEquals(this.LossStreetNoField, value) != true)) {
                    this.LossStreetNoField = value;
                    this.RaisePropertyChanged("LossStreetNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReadStatus {
            get {
                return this.ReadStatusField;
            }
            set {
                if ((this.ReadStatusField.Equals(value) != true)) {
                    this.ReadStatusField = value;
                    this.RaisePropertyChanged("ReadStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReportingDate {
            get {
                return this.ReportingDateField;
            }
            set {
                if ((this.ReportingDateField.Equals(value) != true)) {
                    this.ReportingDateField = value;
                    this.RaisePropertyChanged("ReportingDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubrogationCarChassisNo {
            get {
                return this.SubrogationCarChassisNoField;
            }
            set {
                if ((object.ReferenceEquals(this.SubrogationCarChassisNoField, value) != true)) {
                    this.SubrogationCarChassisNoField = value;
                    this.RaisePropertyChanged("SubrogationCarChassisNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubrogationCarPlateNo {
            get {
                return this.SubrogationCarPlateNoField;
            }
            set {
                if ((object.ReferenceEquals(this.SubrogationCarPlateNoField, value) != true)) {
                    this.SubrogationCarPlateNoField = value;
                    this.RaisePropertyChanged("SubrogationCarPlateNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubrogationGuiltyPartner {
            get {
                return this.SubrogationGuiltyPartnerField;
            }
            set {
                if ((object.ReferenceEquals(this.SubrogationGuiltyPartnerField, value) != true)) {
                    this.SubrogationGuiltyPartnerField = value;
                    this.RaisePropertyChanged("SubrogationGuiltyPartner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubrogationInsurerCountry {
            get {
                return this.SubrogationInsurerCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.SubrogationInsurerCountryField, value) != true)) {
                    this.SubrogationInsurerCountryField = value;
                    this.RaisePropertyChanged("SubrogationInsurerCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubrogationInsurerCountryId {
            get {
                return this.SubrogationInsurerCountryIdField;
            }
            set {
                if ((this.SubrogationInsurerCountryIdField.Equals(value) != true)) {
                    this.SubrogationInsurerCountryIdField = value;
                    this.RaisePropertyChanged("SubrogationInsurerCountryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubrogationInsurerId {
            get {
                return this.SubrogationInsurerIdField;
            }
            set {
                if ((this.SubrogationInsurerIdField.Equals(value) != true)) {
                    this.SubrogationInsurerIdField = value;
                    this.RaisePropertyChanged("SubrogationInsurerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubrogationInsurerName {
            get {
                return this.SubrogationInsurerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SubrogationInsurerNameField, value) != true)) {
                    this.SubrogationInsurerNameField = value;
                    this.RaisePropertyChanged("SubrogationInsurerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubrogationRcoPolicyNo {
            get {
                return this.SubrogationRcoPolicyNoField;
            }
            set {
                if ((object.ReferenceEquals(this.SubrogationRcoPolicyNoField, value) != true)) {
                    this.SubrogationRcoPolicyNoField = value;
                    this.RaisePropertyChanged("SubrogationRcoPolicyNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubrogationType {
            get {
                return this.SubrogationTypeField;
            }
            set {
                if ((this.SubrogationTypeField.Equals(value) != true)) {
                    this.SubrogationTypeField = value;
                    this.RaisePropertyChanged("SubrogationType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClaimDocumentSummary", Namespace="http://schemas.datacontract.org/2004/07/AZT.NET.Insurance.Entities.Claim")]
    [System.SerializableAttribute()]
    public partial class ClaimDocumentSummary : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extension {
            get {
                return this.ExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionField, value) != true)) {
                    this.ExtensionField = value;
                    this.RaisePropertyChanged("Extension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityBase", Namespace="http://schemas.datacontract.org/2004/07/AZT.NET.Common.Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ExternalServiceCalls.ServiceReference1.BinaryContent))]
    public partial class EntityBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BinaryContent", Namespace="http://schemas.datacontract.org/2004/07/AZT.NET.Insurance.Entities")]
    [System.SerializableAttribute()]
    public partial class BinaryContent : ExternalServiceCalls.ServiceReference1.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExternalServiceCalls.ServiceReference1.AZTObjectType AztObjectTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BinaryDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CallerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExternalServiceCalls.ServiceReference1.BinaryContentType ContentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DigitallySignedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IpAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ObjectIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ObjectclassVersionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SealIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExternalServiceCalls.ServiceReference1.AZTObjectType AztObjectType {
            get {
                return this.AztObjectTypeField;
            }
            set {
                if ((this.AztObjectTypeField.Equals(value) != true)) {
                    this.AztObjectTypeField = value;
                    this.RaisePropertyChanged("AztObjectType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] BinaryData {
            get {
                return this.BinaryDataField;
            }
            set {
                if ((object.ReferenceEquals(this.BinaryDataField, value) != true)) {
                    this.BinaryDataField = value;
                    this.RaisePropertyChanged("BinaryData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CallerId {
            get {
                return this.CallerIdField;
            }
            set {
                if ((this.CallerIdField.Equals(value) != true)) {
                    this.CallerIdField = value;
                    this.RaisePropertyChanged("CallerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryType {
            get {
                return this.CategoryTypeField;
            }
            set {
                if ((this.CategoryTypeField.Equals(value) != true)) {
                    this.CategoryTypeField = value;
                    this.RaisePropertyChanged("CategoryType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExternalServiceCalls.ServiceReference1.BinaryContentType ContentType {
            get {
                return this.ContentTypeField;
            }
            set {
                if ((this.ContentTypeField.Equals(value) != true)) {
                    this.ContentTypeField = value;
                    this.RaisePropertyChanged("ContentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DigitallySigned {
            get {
                return this.DigitallySignedField;
            }
            set {
                if ((this.DigitallySignedField.Equals(value) != true)) {
                    this.DigitallySignedField = value;
                    this.RaisePropertyChanged("DigitallySigned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extension {
            get {
                return this.ExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionField, value) != true)) {
                    this.ExtensionField = value;
                    this.RaisePropertyChanged("Extension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IpAddress {
            get {
                return this.IpAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.IpAddressField, value) != true)) {
                    this.IpAddressField = value;
                    this.RaisePropertyChanged("IpAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ObjectId {
            get {
                return this.ObjectIdField;
            }
            set {
                if ((this.ObjectIdField.Equals(value) != true)) {
                    this.ObjectIdField = value;
                    this.RaisePropertyChanged("ObjectId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ObjectclassVersionId {
            get {
                return this.ObjectclassVersionIdField;
            }
            set {
                if ((this.ObjectclassVersionIdField.Equals(value) != true)) {
                    this.ObjectclassVersionIdField = value;
                    this.RaisePropertyChanged("ObjectclassVersionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SealId {
            get {
                return this.SealIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SealIdField, value) != true)) {
                    this.SealIdField = value;
                    this.RaisePropertyChanged("SealId");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AZTObjectType", Namespace="http://schemas.datacontract.org/2004/07/AZT.NET.StarStorage.Entities")]
    public enum AZTObjectType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Policy = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Claim = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Contract = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LifePolicy = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LifeOffer = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClaimReserve = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClaimNotification = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClaimReassessment = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InfoOffice = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RepairShopProfile = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WarningLetter = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AgentsListPerformance = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BordereauBill = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClaimLetter = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartnerAgreement = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TestFile = 100,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BinaryContentType", Namespace="http://schemas.datacontract.org/2004/07/AZT.NET.Insurance.Entities")]
    public enum BinaryContentType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Image = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Document = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISubrogationService")]
    public interface ISubrogationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubrogationService/BrowseAllSubrogations", ReplyAction="http://tempuri.org/ISubrogationService/BrowseAllSubrogationsResponse")]
        ExternalServiceCalls.ServiceReference1.SubrogationInfo[] BrowseAllSubrogations(System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubrogationService/BrowseAllSubrogations", ReplyAction="http://tempuri.org/ISubrogationService/BrowseAllSubrogationsResponse")]
        System.Threading.Tasks.Task<ExternalServiceCalls.ServiceReference1.SubrogationInfo[]> BrowseAllSubrogationsAsync(System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubrogationService/BrowseUnreadSubrogations", ReplyAction="http://tempuri.org/ISubrogationService/BrowseUnreadSubrogationsResponse")]
        ExternalServiceCalls.ServiceReference1.SubrogationInfo[] BrowseUnreadSubrogations(System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubrogationService/BrowseUnreadSubrogations", ReplyAction="http://tempuri.org/ISubrogationService/BrowseUnreadSubrogationsResponse")]
        System.Threading.Tasks.Task<ExternalServiceCalls.ServiceReference1.SubrogationInfo[]> BrowseUnreadSubrogationsAsync(System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubrogationService/MarkAsReadById", ReplyAction="http://tempuri.org/ISubrogationService/MarkAsReadByIdResponse")]
        void MarkAsReadById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubrogationService/MarkAsReadById", ReplyAction="http://tempuri.org/ISubrogationService/MarkAsReadByIdResponse")]
        System.Threading.Tasks.Task MarkAsReadByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubrogationService/MarkAsReadByClaimId", ReplyAction="http://tempuri.org/ISubrogationService/MarkAsReadByClaimIdResponse")]
        void MarkAsReadByClaimId(int claimId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubrogationService/MarkAsReadByClaimId", ReplyAction="http://tempuri.org/ISubrogationService/MarkAsReadByClaimIdResponse")]
        System.Threading.Tasks.Task MarkAsReadByClaimIdAsync(int claimId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubrogationService/MarkAsReadByClaimFileNo", ReplyAction="http://tempuri.org/ISubrogationService/MarkAsReadByClaimFileNoResponse")]
        void MarkAsReadByClaimFileNo(string claimFileNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubrogationService/MarkAsReadByClaimFileNo", ReplyAction="http://tempuri.org/ISubrogationService/MarkAsReadByClaimFileNoResponse")]
        System.Threading.Tasks.Task MarkAsReadByClaimFileNoAsync(string claimFileNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubrogationService/BrowseClaimDocuments", ReplyAction="http://tempuri.org/ISubrogationService/BrowseClaimDocumentsResponse")]
        ExternalServiceCalls.ServiceReference1.ClaimDocumentSummary[] BrowseClaimDocuments(int claimId, System.DateTime startDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubrogationService/BrowseClaimDocuments", ReplyAction="http://tempuri.org/ISubrogationService/BrowseClaimDocumentsResponse")]
        System.Threading.Tasks.Task<ExternalServiceCalls.ServiceReference1.ClaimDocumentSummary[]> BrowseClaimDocumentsAsync(int claimId, System.DateTime startDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubrogationService/GetClaimDocumentDetails", ReplyAction="http://tempuri.org/ISubrogationService/GetClaimDocumentDetailsResponse")]
        ExternalServiceCalls.ServiceReference1.BinaryContent GetClaimDocumentDetails(int documentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubrogationService/GetClaimDocumentDetails", ReplyAction="http://tempuri.org/ISubrogationService/GetClaimDocumentDetailsResponse")]
        System.Threading.Tasks.Task<ExternalServiceCalls.ServiceReference1.BinaryContent> GetClaimDocumentDetailsAsync(int documentId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISubrogationServiceChannel : ExternalServiceCalls.ServiceReference1.ISubrogationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubrogationServiceClient : System.ServiceModel.ClientBase<ExternalServiceCalls.ServiceReference1.ISubrogationService>, ExternalServiceCalls.ServiceReference1.ISubrogationService {
        
        public SubrogationServiceClient() {
        }
        
        public SubrogationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SubrogationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubrogationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubrogationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ExternalServiceCalls.ServiceReference1.SubrogationInfo[] BrowseAllSubrogations(System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.BrowseAllSubrogations(startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<ExternalServiceCalls.ServiceReference1.SubrogationInfo[]> BrowseAllSubrogationsAsync(System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.BrowseAllSubrogationsAsync(startDate, endDate);
        }
        
        public ExternalServiceCalls.ServiceReference1.SubrogationInfo[] BrowseUnreadSubrogations(System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.BrowseUnreadSubrogations(startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<ExternalServiceCalls.ServiceReference1.SubrogationInfo[]> BrowseUnreadSubrogationsAsync(System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.BrowseUnreadSubrogationsAsync(startDate, endDate);
        }
        
        public void MarkAsReadById(int id) {
            base.Channel.MarkAsReadById(id);
        }
        
        public System.Threading.Tasks.Task MarkAsReadByIdAsync(int id) {
            return base.Channel.MarkAsReadByIdAsync(id);
        }
        
        public void MarkAsReadByClaimId(int claimId) {
            base.Channel.MarkAsReadByClaimId(claimId);
        }
        
        public System.Threading.Tasks.Task MarkAsReadByClaimIdAsync(int claimId) {
            return base.Channel.MarkAsReadByClaimIdAsync(claimId);
        }
        
        public void MarkAsReadByClaimFileNo(string claimFileNo) {
            base.Channel.MarkAsReadByClaimFileNo(claimFileNo);
        }
        
        public System.Threading.Tasks.Task MarkAsReadByClaimFileNoAsync(string claimFileNo) {
            return base.Channel.MarkAsReadByClaimFileNoAsync(claimFileNo);
        }
        
        public ExternalServiceCalls.ServiceReference1.ClaimDocumentSummary[] BrowseClaimDocuments(int claimId, System.DateTime startDate) {
            return base.Channel.BrowseClaimDocuments(claimId, startDate);
        }
        
        public System.Threading.Tasks.Task<ExternalServiceCalls.ServiceReference1.ClaimDocumentSummary[]> BrowseClaimDocumentsAsync(int claimId, System.DateTime startDate) {
            return base.Channel.BrowseClaimDocumentsAsync(claimId, startDate);
        }
        
        public ExternalServiceCalls.ServiceReference1.BinaryContent GetClaimDocumentDetails(int documentId) {
            return base.Channel.GetClaimDocumentDetails(documentId);
        }
        
        public System.Threading.Tasks.Task<ExternalServiceCalls.ServiceReference1.BinaryContent> GetClaimDocumentDetailsAsync(int documentId) {
            return base.Channel.GetClaimDocumentDetailsAsync(documentId);
        }
    }
}
